name: CraftBook (mechanisms)
main: com.sk89q.craftbook.bukkit.MechanismsPlugin
version: __VERSION_MACRO__
commands:
    savearea:
        description: Save an area
        usage: /<command>
    savensarea:
        description: Save an area with a custom namespace
        usage: /<command>
    area:
        description: Toggle area commands
        usage: /<command>