name: CraftBook5
version: "${internalVersion}"
main: org.enginehub.craftbook.bukkit.CraftBookPlugin
author: EngineHub
api-version: "1.21"
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
    WorldGuard:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
