name: CraftBook
main: com.sk89q.craftbook.bukkit.CraftBookPlugin
version: "${project.version}"
dev-url: http://dev.bukkit.org/server-mods/craftbook/
depend: [WorldEdit]
softdepend: [WorldGuard, ProtocolLib, Vault]
commands:
