name: CraftBook
main: com.sk89q.craftbook.bukkit.CraftBookPlugin
version: "${internalVersion}"
dev-url: https://dev.bukkit.org/projects/craftbook
softdepend: [WorldEdit, WorldGuard, ProtocolLib, Vault]
api-version: 1.18
commands:
