control-blocks: true
max-boost-block: 41
25x-boost-block: 14
50x-slow-block: 88
20x-slow-block: 13
station-block: 49
reverse-block: 35
deposit-block: 15
eject-block: 42
teleport-block: 89
sort-block: 87
minecart-remove-entities: false
minecart-remove-on-exit: false
minecart-dispensers: true
minecart-decay-time: 0
minecart-slow-when-empty: false
minecart-max-speed-modifier: 1
in-cart-control: true
hinder-pressure-plate-slow: true

boat-break-return-boat: false
boat-remove-entities: false