name: CraftBookCircuits
main: com.sk89q.craftbook.bukkit.CircuitsPlugin
version: "${project.version}"
depend: [CraftBookCommon]
commands:
    ic:
        description: IC-related commands
        usage: /<command>
    listics:
        description: List the ICs available
        usage: /<command>