name: CraftBookMechanisms
main: com.sk89q.craftbook.bukkit.MechanismsPlugin
version: "${project.version}"
depend: [CraftBookCommon]
commands:
    savearea:
        description: Save an area
        usage: /<command>
    savensarea:
        description: Save an area with a custom namespace
        usage: /<command>
    area:
        description: Toggle area commands
        usage: /<command>
    cbmech:
        description: Reload configuration
        usage: /<command> <reload>